### ISSUE TITLE
Add URL to repo page

### ISSUE THREAD

**Issue by cvan** [toji/webvr-samples#14]
Next to the description, we should add the URL: https://toji.github.io/webvr-samples/

**Comment by cvan** [comment]
@toji can you just add the URL here:

![image](https://cloud.githubusercontent.com/assets/203725/14306424/d3ee07a0-fb7b-11e5-8b21-39cdb3e2697c.png)

**Comment by toji** [comment]
Hm... not sure how I've completely missed this issue till now. Sorry! Added the URL. (I went with the webvr.info/samples/ variant, since it's easier to remember)
