### ISSUE TITLE
None of the examples go fullscreen on iPhone 5C

### ISSUE THREAD

**Issue by vorg** [toji/webvr-samples#18]
Somehow the dom or canvas resizing breaks the fullscreen on iOS. I need to add proper meta tags on iOS and add example page to home screen to get fullscreen in landscape mode.

```
<meta name="apple-mobile-web-app-capable" content="yes">
```

It's the same issue as https://github.com/aframevr/aframe/issues/967 
Video showing the behavior https://vimeo.com/155153964/48dd611c61

This page http://vr.chromeexperiments.com works just fine without modifying anything.

**Comment by toji** [comment]
Thanks for the suggestion! I wasn't aware that this was an option!
