### ISSUE TITLE
Copyright notice necessary?

### ISSUE THREAD

**Issue by cvan** [toji/webvr-samples#2]
I noticed all the non-third-party `.js` files (such as [this one](https://github.com/toji/webvr-samples/blob/gh-pages/js/vr-samples-util.js)) and `.html` files (such as [this one](https://github.com/toji/webvr-samples/blob/gh-pages/00-hello-webvr.html)) have copyright notices as comments.

If one were to fork or copy this code to another project, would the copyright notice need to remain intact? Even if the code was altered significantly?

If it's not necessary, can the copyright notices be removed from this repo? And instead I'd recommend just adding the MIT License in a `LICENSE` file (and link to it from the `README.md`).

**Comment by toji** [comment]
Copyright has been changed over to the Chromium standard one, but that will have to remain in place.
