### ISSUE TITLE
"Your browser does not support WebVR" in Samsung Gear Vr browser - Oculus Rift

### ISSUE THREAD

**Issue by ranbuch** [toji/webvr-samples#28]
Hi,

None of the links from this page:
https://webvr.info/samples/
works on my Samsung Galaxy s7 Edge with the Gear-Vr set and "Samsung Internet" browser app.

How can I get support for web-vr in Gear-VR?

Thank you.

**Comment by toji** [comment]
I believe at this point that the Samsung browser supports an older version of the WebVR spec, which these samples aren't compatible with. This should be a temporary issue, though I can't provide any timelines for Samsung's work.

**Comment by ranbuch** [comment]
Extreamlly anoing seens I bought this phone mainlly to d
